import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Download, FileSpreadsheet, Mail, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable, type DataTableColumn } from "@/components/data/data-table";
import { StatusBadge, type StatusTone } from "@/components/feedback/status-badge";
import { formatDate } from "@/lib/format";
import { REPORT_TYPE_LABEL, REPORT_TYPE_ENDPOINT, type ReportType, type ReportFormat, type ReportHistoryRow, type ReportStatus } from "../types";

interface ClientOption {
  id: string;
  fullName: string;
  email?: string;
}

interface Props {
  clients: ClientOption[];
  history: ReportHistoryRow[];
  isLoading?: boolean;
  ownerLabel: string;
}

const STATUS_TONE: Record<ReportStatus, StatusTone> = {
  ready: "success",
  processing: "info",
  failed: "destructive",
};

const schema = z
  .object({
    clientId: z.string().min(1, "Select a client"),
    reportType: z.enum(["wealth", "pl", "capital_gains", "transaction", "holding"]),
    fromDate: z.string().min(1, "From date required"),
    toDate: z.string().min(1, "To date required"),
    format: z.enum(["pdf", "excel", "csv"]),
  })
  .refine((v) => new Date(v.fromDate) <= new Date(v.toDate), {
    message: "From date must be before To date",
    path: ["toDate"],
  });

type FormValues = z.infer<typeof schema>;

function defaultFY(): { from: string; to: string } {
  const now = new Date("2026-04-16");
  const fyStartYear = now.getMonth() >= 3 ? now.getFullYear() - 1 : now.getFullYear() - 2;
  return {
    from: `${fyStartYear}-04-01`,
    to: now.toISOString().slice(0, 10),
  };
}

function downloadCsv(filename: string, rows: string[][]) {
  const csv = rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function ClientReportsForm({ clients, history, isLoading, ownerLabel }: Props) {
  const fy = defaultFY();
  const [clientSearch, setClientSearch] = useState("");
  const form = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: { clientId: "", reportType: "wealth", fromDate: fy.from, toDate: fy.to, format: "pdf" },
  });

  const filteredClients = useMemo(() => {
    const q = clientSearch.trim().toLowerCase();
    if (!q) return clients.slice(0, 50);
    return clients.filter((c) => `${c.fullName} ${c.email ?? ""}`.toLowerCase().includes(q)).slice(0, 50);
  }, [clients, clientSearch]);

  function onSubmit(values: FormValues) {
    const client = clients.find((c) => c.id === values.clientId);
    const endpoint = REPORT_TYPE_ENDPOINT[values.reportType];
    const label = REPORT_TYPE_LABEL[values.reportType];
    downloadCsv(
      `${label.replace(/\s+/g, "_")}_${client?.fullName.replace(/\s+/g, "_") ?? "client"}_${values.fromDate}_${values.toDate}.csv`,
      [
        ["Report", label],
        ["Client", client?.fullName ?? values.clientId],
        ["Period", `${values.fromDate} to ${values.toDate}`],
        ["Format requested", values.format.toUpperCase()],
        ["Generated by", ownerLabel],
        ["Backend endpoint", endpoint],
      ],
    );
    toast.success(`${label} generated`, { description: `Would call ${endpoint} for ${client?.fullName}` });
  }

  function emailClient() {
    const values = form.getValues();
    const client = clients.find((c) => c.id === values.clientId);
    if (!client) {
      toast.error("Select a client first");
      return;
    }
    toast.success(`Report queued to email`, { description: `${REPORT_TYPE_LABEL[values.reportType]} → ${client.fullName}` });
  }

  const columns: DataTableColumn<ReportHistoryRow>[] = [
    { id: "client", header: "Client", sortValue: (r) => r.clientName, accessor: (r) => <span className="font-semibold">{r.clientName}</span> },
    { id: "type", header: "Report", sortValue: (r) => r.type, accessor: (r) => REPORT_TYPE_LABEL[r.type] },
    {
      id: "period",
      header: "Period",
      sortValue: (r) => r.fromDate,
      accessor: (r) => (
        <span className="text-sm text-muted-foreground">
          {formatDate(r.fromDate)} – {formatDate(r.toDate)}
        </span>
      ),
    },
    { id: "format", header: "Format", sortValue: (r) => r.format, accessor: (r) => <span className="uppercase text-xs font-medium">{r.format}</span> },
    { id: "status", header: "Status", sortValue: (r) => r.status, accessor: (r) => <StatusBadge tone={STATUS_TONE[r.status]} label={r.status} /> },
    { id: "at", header: "Generated", sortValue: (r) => r.generatedAt, accessor: (r) => <span className="text-muted-foreground text-sm">{formatDate(r.generatedAt)}</span> },
  ];

  return (
    <div className="space-y-6">
      <Card className="shadow-card">
        <CardHeader>
          <div className="flex items-start justify-between gap-3">
            <div>
              <CardTitle>Generate report</CardTitle>
              <CardDescription>Pick a client, report, period and format. Download or email it directly.</CardDescription>
            </div>
            <div className="grid h-10 w-10 place-items-center rounded-xl gradient-brand text-primary-foreground shadow-glow">
              <FileSpreadsheet className="h-4.5 w-4.5" />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <form className="grid gap-4 md:grid-cols-2 lg:grid-cols-3" onSubmit={form.handleSubmit(onSubmit)}>
            <div className="space-y-2 lg:col-span-3">
              <Label>Client</Label>
              <div className="relative">
                <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  value={clientSearch}
                  onChange={(e) => setClientSearch(e.target.value)}
                  placeholder="Search clients by name or email…"
                  className="pl-9"
                />
              </div>
              <Select value={form.watch("clientId")} onValueChange={(v) => form.setValue("clientId", v, { shouldValidate: true })}>
                <SelectTrigger><SelectValue placeholder="Select a client" /></SelectTrigger>
                <SelectContent>
                  {filteredClients.map((c) => (
                    <SelectItem key={c.id} value={c.id}>
                      {c.fullName}{c.email ? ` · ${c.email}` : ""}
                    </SelectItem>
                  ))}
                  {filteredClients.length === 0 && <div className="p-2 text-sm text-muted-foreground">No matches</div>}
                </SelectContent>
              </Select>
              {form.formState.errors.clientId && (
                <p className="text-xs text-destructive">{form.formState.errors.clientId.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label>Report type</Label>
              <Select value={form.watch("reportType")} onValueChange={(v) => form.setValue("reportType", v as ReportType)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {(Object.keys(REPORT_TYPE_LABEL) as ReportType[]).map((t) => (
                    <SelectItem key={t} value={t}>{REPORT_TYPE_LABEL[t]}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>From date</Label>
              <Input type="date" {...form.register("fromDate")} />
            </div>

            <div className="space-y-2">
              <Label>To date</Label>
              <Input type="date" {...form.register("toDate")} />
              {form.formState.errors.toDate && (
                <p className="text-xs text-destructive">{form.formState.errors.toDate.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label>Format</Label>
              <Select value={form.watch("format")} onValueChange={(v) => form.setValue("format", v as ReportFormat)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="pdf">PDF</SelectItem>
                  <SelectItem value="excel">Excel</SelectItem>
                  <SelectItem value="csv">CSV</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-end gap-2 lg:col-span-2">
              <Button type="submit" className="gap-2"><Download className="h-4 w-4" /> Generate &amp; download</Button>
              <Button type="button" variant="outline" className="gap-2" onClick={emailClient}>
                <Mail className="h-4 w-4" /> Email to client
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      <Card className="shadow-card">
        <CardHeader>
          <CardTitle>Recent exports</CardTitle>
          <CardDescription>Reports generated in the last 60 days.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="p-6 text-center text-sm text-muted-foreground">Loading history…</p>
          ) : (
            <DataTable columns={columns} data={history} initialSortId="at" pageSize={8} />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
