/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppRmIndexRouteImport } from './routes/app.rm.index'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as AppDistributorIndexRouteImport } from './routes/app.distributor.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppRmOrdersRouteImport } from './routes/app.rm.orders'
import { Route as AppRmOnboardingRouteImport } from './routes/app.rm.onboarding'
import { Route as AppRmEarningsRouteImport } from './routes/app.rm.earnings'
import { Route as AppRmDistributorsRouteImport } from './routes/app.rm.distributors'
import { Route as AppRmClientsRouteImport } from './routes/app.rm.clients'
import { Route as AppInvestorTransactionsRouteImport } from './routes/app.investor.transactions'
import { Route as AppInvestorTaxRouteImport } from './routes/app.investor.tax'
import { Route as AppInvestorProfileRouteImport } from './routes/app.investor.profile'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorGoalsRouteImport } from './routes/app.investor.goals'
import { Route as AppDistributorOrdersRouteImport } from './routes/app.distributor.orders'
import { Route as AppDistributorOnboardingRouteImport } from './routes/app.distributor.onboarding'
import { Route as AppDistributorCommissionsRouteImport } from './routes/app.distributor.commissions'
import { Route as AppDistributorAumRouteImport } from './routes/app.distributor.aum'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSystemConfigRouteImport } from './routes/app.admin.system-config'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminRmsRouteImport } from './routes/app.admin.rms'
import { Route as AppAdminReconciliationRouteImport } from './routes/app.admin.reconciliation'
import { Route as AppAdminPayoutsRouteImport } from './routes/app.admin.payouts'
import { Route as AppAdminOrdersRouteImport } from './routes/app.admin.orders'
import { Route as AppAdminOnboardingRouteImport } from './routes/app.admin.onboarding'
import { Route as AppAdminMasterDataRouteImport } from './routes/app.admin.master-data'
import { Route as AppAdminMappingsRouteImport } from './routes/app.admin.mappings'
import { Route as AppAdminDistributorsRouteImport } from './routes/app.admin.distributors'
import { Route as AppAdminDistributorCategoriesRouteImport } from './routes/app.admin.distributor-categories'
import { Route as AppAdminCommissionsRouteImport } from './routes/app.admin.commissions'
import { Route as AppAdminBrokerageImportsRouteImport } from './routes/app.admin.brokerage-imports'
import { Route as AppAdminBranchesRouteImport } from './routes/app.admin.branches'
import { Route as AppRmOrdersNewRouteImport } from './routes/app.rm.orders.new'
import { Route as AppRmOnboardingNewRouteImport } from './routes/app.rm.onboarding.new'
import { Route as AppRmDistributorsNewRouteImport } from './routes/app.rm.distributors.new'
import { Route as AppInvestorPortfolioHoldingIdRouteImport } from './routes/app.investor.portfolio.$holdingId'
import { Route as AppDistributorOrdersNewRouteImport } from './routes/app.distributor.orders.new'
import { Route as AppDistributorOnboardingNewRouteImport } from './routes/app.distributor.onboarding.new'
import { Route as AppAdminRmsNewRouteImport } from './routes/app.admin.rms.new'
import { Route as AppAdminOrdersNewRouteImport } from './routes/app.admin.orders.new'
import { Route as AppAdminOnboardingNewRouteImport } from './routes/app.admin.onboarding.new'
import { Route as AppAdminDistributorsNewRouteImport } from './routes/app.admin.distributors.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRmIndexRoute = AppRmIndexRouteImport.update({
  id: '/rm/',
  path: '/rm/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorIndexRoute = AppDistributorIndexRouteImport.update({
  id: '/distributor/',
  path: '/distributor/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppRmOrdersRoute = AppRmOrdersRouteImport.update({
  id: '/rm/orders',
  path: '/rm/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRmOnboardingRoute = AppRmOnboardingRouteImport.update({
  id: '/rm/onboarding',
  path: '/rm/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppRmEarningsRoute = AppRmEarningsRouteImport.update({
  id: '/rm/earnings',
  path: '/rm/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppRmDistributorsRoute = AppRmDistributorsRouteImport.update({
  id: '/rm/distributors',
  path: '/rm/distributors',
  getParentRoute: () => AppRoute,
} as any)
const AppRmClientsRoute = AppRmClientsRouteImport.update({
  id: '/rm/clients',
  path: '/rm/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTransactionsRoute = AppInvestorTransactionsRouteImport.update({
  id: '/investor/transactions',
  path: '/investor/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTaxRoute = AppInvestorTaxRouteImport.update({
  id: '/investor/tax',
  path: '/investor/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorProfileRoute = AppInvestorProfileRouteImport.update({
  id: '/investor/profile',
  path: '/investor/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorGoalsRoute = AppInvestorGoalsRouteImport.update({
  id: '/investor/goals',
  path: '/investor/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorOrdersRoute = AppDistributorOrdersRouteImport.update({
  id: '/distributor/orders',
  path: '/distributor/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorOnboardingRoute =
  AppDistributorOnboardingRouteImport.update({
    id: '/distributor/onboarding',
    path: '/distributor/onboarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppDistributorCommissionsRoute =
  AppDistributorCommissionsRouteImport.update({
    id: '/distributor/commissions',
    path: '/distributor/commissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppDistributorAumRoute = AppDistributorAumRouteImport.update({
  id: '/distributor/aum',
  path: '/distributor/aum',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemConfigRoute = AppAdminSystemConfigRouteImport.update({
  id: '/admin/system-config',
  path: '/admin/system-config',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRmsRoute = AppAdminRmsRouteImport.update({
  id: '/admin/rms',
  path: '/admin/rms',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReconciliationRoute = AppAdminReconciliationRouteImport.update({
  id: '/admin/reconciliation',
  path: '/admin/reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrdersRoute = AppAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnboardingRoute = AppAdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMasterDataRoute = AppAdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMappingsRoute = AppAdminMappingsRouteImport.update({
  id: '/admin/mappings',
  path: '/admin/mappings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDistributorsRoute = AppAdminDistributorsRouteImport.update({
  id: '/admin/distributors',
  path: '/admin/distributors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDistributorCategoriesRoute =
  AppAdminDistributorCategoriesRouteImport.update({
    id: '/admin/distributor-categories',
    path: '/admin/distributor-categories',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminCommissionsRoute = AppAdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBrokerageImportsRoute =
  AppAdminBrokerageImportsRouteImport.update({
    id: '/admin/brokerage-imports',
    path: '/admin/brokerage-imports',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppRmOrdersNewRoute = AppRmOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRmOrdersRoute,
} as any)
const AppRmOnboardingNewRoute = AppRmOnboardingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRmOnboardingRoute,
} as any)
const AppRmDistributorsNewRoute = AppRmDistributorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRmDistributorsRoute,
} as any)
const AppInvestorPortfolioHoldingIdRoute =
  AppInvestorPortfolioHoldingIdRouteImport.update({
    id: '/$holdingId',
    path: '/$holdingId',
    getParentRoute: () => AppInvestorPortfolioRoute,
  } as any)
const AppDistributorOrdersNewRoute = AppDistributorOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDistributorOrdersRoute,
} as any)
const AppDistributorOnboardingNewRoute =
  AppDistributorOnboardingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppDistributorOnboardingRoute,
  } as any)
const AppAdminRmsNewRoute = AppAdminRmsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminRmsRoute,
} as any)
const AppAdminOrdersNewRoute = AppAdminOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminOrdersRoute,
} as any)
const AppAdminOnboardingNewRoute = AppAdminOnboardingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminOnboardingRoute,
} as any)
const AppAdminDistributorsNewRoute = AppAdminDistributorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminDistributorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/brokerage-imports': typeof AppAdminBrokerageImportsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributor-categories': typeof AppAdminDistributorCategoriesRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRouteWithChildren
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRouteWithChildren
  '/app/admin/orders': typeof AppAdminOrdersRouteWithChildren
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/system-config': typeof AppAdminSystemConfigRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRouteWithChildren
  '/app/distributor/orders': typeof AppDistributorOrdersRouteWithChildren
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRouteWithChildren
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRouteWithChildren
  '/app/rm/orders': typeof AppRmOrdersRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/admin/distributors/new': typeof AppAdminDistributorsNewRoute
  '/app/admin/onboarding/new': typeof AppAdminOnboardingNewRoute
  '/app/admin/orders/new': typeof AppAdminOrdersNewRoute
  '/app/admin/rms/new': typeof AppAdminRmsNewRoute
  '/app/distributor/onboarding/new': typeof AppDistributorOnboardingNewRoute
  '/app/distributor/orders/new': typeof AppDistributorOrdersNewRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
  '/app/rm/distributors/new': typeof AppRmDistributorsNewRoute
  '/app/rm/onboarding/new': typeof AppRmOnboardingNewRoute
  '/app/rm/orders/new': typeof AppRmOrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/brokerage-imports': typeof AppAdminBrokerageImportsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributor-categories': typeof AppAdminDistributorCategoriesRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRouteWithChildren
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRouteWithChildren
  '/app/admin/orders': typeof AppAdminOrdersRouteWithChildren
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/system-config': typeof AppAdminSystemConfigRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRouteWithChildren
  '/app/distributor/orders': typeof AppDistributorOrdersRouteWithChildren
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRouteWithChildren
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRouteWithChildren
  '/app/rm/orders': typeof AppRmOrdersRouteWithChildren
  '/app/admin': typeof AppAdminIndexRoute
  '/app/distributor': typeof AppDistributorIndexRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/rm': typeof AppRmIndexRoute
  '/app/admin/distributors/new': typeof AppAdminDistributorsNewRoute
  '/app/admin/onboarding/new': typeof AppAdminOnboardingNewRoute
  '/app/admin/orders/new': typeof AppAdminOrdersNewRoute
  '/app/admin/rms/new': typeof AppAdminRmsNewRoute
  '/app/distributor/onboarding/new': typeof AppDistributorOnboardingNewRoute
  '/app/distributor/orders/new': typeof AppDistributorOrdersNewRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
  '/app/rm/distributors/new': typeof AppRmDistributorsNewRoute
  '/app/rm/onboarding/new': typeof AppRmOnboardingNewRoute
  '/app/rm/orders/new': typeof AppRmOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/brokerage-imports': typeof AppAdminBrokerageImportsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributor-categories': typeof AppAdminDistributorCategoriesRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRouteWithChildren
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRouteWithChildren
  '/app/admin/orders': typeof AppAdminOrdersRouteWithChildren
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/system-config': typeof AppAdminSystemConfigRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRouteWithChildren
  '/app/distributor/orders': typeof AppDistributorOrdersRouteWithChildren
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRouteWithChildren
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRouteWithChildren
  '/app/rm/orders': typeof AppRmOrdersRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/admin/distributors/new': typeof AppAdminDistributorsNewRoute
  '/app/admin/onboarding/new': typeof AppAdminOnboardingNewRoute
  '/app/admin/orders/new': typeof AppAdminOrdersNewRoute
  '/app/admin/rms/new': typeof AppAdminRmsNewRoute
  '/app/distributor/onboarding/new': typeof AppDistributorOnboardingNewRoute
  '/app/distributor/orders/new': typeof AppDistributorOrdersNewRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
  '/app/rm/distributors/new': typeof AppRmDistributorsNewRoute
  '/app/rm/onboarding/new': typeof AppRmOnboardingNewRoute
  '/app/rm/orders/new': typeof AppRmOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/brokerage-imports'
    | '/app/admin/commissions'
    | '/app/admin/distributor-categories'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/orders'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/system-config'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/distributor/orders'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/rm/orders'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/admin/distributors/new'
    | '/app/admin/onboarding/new'
    | '/app/admin/orders/new'
    | '/app/admin/rms/new'
    | '/app/distributor/onboarding/new'
    | '/app/distributor/orders/new'
    | '/app/investor/portfolio/$holdingId'
    | '/app/rm/distributors/new'
    | '/app/rm/onboarding/new'
    | '/app/rm/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/brokerage-imports'
    | '/app/admin/commissions'
    | '/app/admin/distributor-categories'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/orders'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/system-config'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/distributor/orders'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/rm/orders'
    | '/app/admin'
    | '/app/distributor'
    | '/app/investor'
    | '/app/rm'
    | '/app/admin/distributors/new'
    | '/app/admin/onboarding/new'
    | '/app/admin/orders/new'
    | '/app/admin/rms/new'
    | '/app/distributor/onboarding/new'
    | '/app/distributor/orders/new'
    | '/app/investor/portfolio/$holdingId'
    | '/app/rm/distributors/new'
    | '/app/rm/onboarding/new'
    | '/app/rm/orders/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/brokerage-imports'
    | '/app/admin/commissions'
    | '/app/admin/distributor-categories'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/orders'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/system-config'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/distributor/orders'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/rm/orders'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/admin/distributors/new'
    | '/app/admin/onboarding/new'
    | '/app/admin/orders/new'
    | '/app/admin/rms/new'
    | '/app/distributor/onboarding/new'
    | '/app/distributor/orders/new'
    | '/app/investor/portfolio/$holdingId'
    | '/app/rm/distributors/new'
    | '/app/rm/onboarding/new'
    | '/app/rm/orders/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/': {
      id: '/app/rm/'
      path: '/rm'
      fullPath: '/app/rm/'
      preLoaderRoute: typeof AppRmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/investor'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/': {
      id: '/app/distributor/'
      path: '/distributor'
      fullPath: '/app/distributor/'
      preLoaderRoute: typeof AppDistributorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/orders': {
      id: '/app/rm/orders'
      path: '/rm/orders'
      fullPath: '/app/rm/orders'
      preLoaderRoute: typeof AppRmOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/onboarding': {
      id: '/app/rm/onboarding'
      path: '/rm/onboarding'
      fullPath: '/app/rm/onboarding'
      preLoaderRoute: typeof AppRmOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/earnings': {
      id: '/app/rm/earnings'
      path: '/rm/earnings'
      fullPath: '/app/rm/earnings'
      preLoaderRoute: typeof AppRmEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/distributors': {
      id: '/app/rm/distributors'
      path: '/rm/distributors'
      fullPath: '/app/rm/distributors'
      preLoaderRoute: typeof AppRmDistributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/clients': {
      id: '/app/rm/clients'
      path: '/rm/clients'
      fullPath: '/app/rm/clients'
      preLoaderRoute: typeof AppRmClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/transactions': {
      id: '/app/investor/transactions'
      path: '/investor/transactions'
      fullPath: '/app/investor/transactions'
      preLoaderRoute: typeof AppInvestorTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/tax': {
      id: '/app/investor/tax'
      path: '/investor/tax'
      fullPath: '/app/investor/tax'
      preLoaderRoute: typeof AppInvestorTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/profile': {
      id: '/app/investor/profile'
      path: '/investor/profile'
      fullPath: '/app/investor/profile'
      preLoaderRoute: typeof AppInvestorProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/goals': {
      id: '/app/investor/goals'
      path: '/investor/goals'
      fullPath: '/app/investor/goals'
      preLoaderRoute: typeof AppInvestorGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/orders': {
      id: '/app/distributor/orders'
      path: '/distributor/orders'
      fullPath: '/app/distributor/orders'
      preLoaderRoute: typeof AppDistributorOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/onboarding': {
      id: '/app/distributor/onboarding'
      path: '/distributor/onboarding'
      fullPath: '/app/distributor/onboarding'
      preLoaderRoute: typeof AppDistributorOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/commissions': {
      id: '/app/distributor/commissions'
      path: '/distributor/commissions'
      fullPath: '/app/distributor/commissions'
      preLoaderRoute: typeof AppDistributorCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/aum': {
      id: '/app/distributor/aum'
      path: '/distributor/aum'
      fullPath: '/app/distributor/aum'
      preLoaderRoute: typeof AppDistributorAumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system-config': {
      id: '/app/admin/system-config'
      path: '/admin/system-config'
      fullPath: '/app/admin/system-config'
      preLoaderRoute: typeof AppAdminSystemConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/rms': {
      id: '/app/admin/rms'
      path: '/admin/rms'
      fullPath: '/app/admin/rms'
      preLoaderRoute: typeof AppAdminRmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/reconciliation': {
      id: '/app/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/app/admin/reconciliation'
      preLoaderRoute: typeof AppAdminReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payouts': {
      id: '/app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/app/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/orders': {
      id: '/app/admin/orders'
      path: '/admin/orders'
      fullPath: '/app/admin/orders'
      preLoaderRoute: typeof AppAdminOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/onboarding': {
      id: '/app/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/app/admin/onboarding'
      preLoaderRoute: typeof AppAdminOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/master-data': {
      id: '/app/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/app/admin/master-data'
      preLoaderRoute: typeof AppAdminMasterDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/mappings': {
      id: '/app/admin/mappings'
      path: '/admin/mappings'
      fullPath: '/app/admin/mappings'
      preLoaderRoute: typeof AppAdminMappingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/distributors': {
      id: '/app/admin/distributors'
      path: '/admin/distributors'
      fullPath: '/app/admin/distributors'
      preLoaderRoute: typeof AppAdminDistributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/distributor-categories': {
      id: '/app/admin/distributor-categories'
      path: '/admin/distributor-categories'
      fullPath: '/app/admin/distributor-categories'
      preLoaderRoute: typeof AppAdminDistributorCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/commissions': {
      id: '/app/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/app/admin/commissions'
      preLoaderRoute: typeof AppAdminCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/brokerage-imports': {
      id: '/app/admin/brokerage-imports'
      path: '/admin/brokerage-imports'
      fullPath: '/app/admin/brokerage-imports'
      preLoaderRoute: typeof AppAdminBrokerageImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/branches': {
      id: '/app/admin/branches'
      path: '/admin/branches'
      fullPath: '/app/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/orders/new': {
      id: '/app/rm/orders/new'
      path: '/new'
      fullPath: '/app/rm/orders/new'
      preLoaderRoute: typeof AppRmOrdersNewRouteImport
      parentRoute: typeof AppRmOrdersRoute
    }
    '/app/rm/onboarding/new': {
      id: '/app/rm/onboarding/new'
      path: '/new'
      fullPath: '/app/rm/onboarding/new'
      preLoaderRoute: typeof AppRmOnboardingNewRouteImport
      parentRoute: typeof AppRmOnboardingRoute
    }
    '/app/rm/distributors/new': {
      id: '/app/rm/distributors/new'
      path: '/new'
      fullPath: '/app/rm/distributors/new'
      preLoaderRoute: typeof AppRmDistributorsNewRouteImport
      parentRoute: typeof AppRmDistributorsRoute
    }
    '/app/investor/portfolio/$holdingId': {
      id: '/app/investor/portfolio/$holdingId'
      path: '/$holdingId'
      fullPath: '/app/investor/portfolio/$holdingId'
      preLoaderRoute: typeof AppInvestorPortfolioHoldingIdRouteImport
      parentRoute: typeof AppInvestorPortfolioRoute
    }
    '/app/distributor/orders/new': {
      id: '/app/distributor/orders/new'
      path: '/new'
      fullPath: '/app/distributor/orders/new'
      preLoaderRoute: typeof AppDistributorOrdersNewRouteImport
      parentRoute: typeof AppDistributorOrdersRoute
    }
    '/app/distributor/onboarding/new': {
      id: '/app/distributor/onboarding/new'
      path: '/new'
      fullPath: '/app/distributor/onboarding/new'
      preLoaderRoute: typeof AppDistributorOnboardingNewRouteImport
      parentRoute: typeof AppDistributorOnboardingRoute
    }
    '/app/admin/rms/new': {
      id: '/app/admin/rms/new'
      path: '/new'
      fullPath: '/app/admin/rms/new'
      preLoaderRoute: typeof AppAdminRmsNewRouteImport
      parentRoute: typeof AppAdminRmsRoute
    }
    '/app/admin/orders/new': {
      id: '/app/admin/orders/new'
      path: '/new'
      fullPath: '/app/admin/orders/new'
      preLoaderRoute: typeof AppAdminOrdersNewRouteImport
      parentRoute: typeof AppAdminOrdersRoute
    }
    '/app/admin/onboarding/new': {
      id: '/app/admin/onboarding/new'
      path: '/new'
      fullPath: '/app/admin/onboarding/new'
      preLoaderRoute: typeof AppAdminOnboardingNewRouteImport
      parentRoute: typeof AppAdminOnboardingRoute
    }
    '/app/admin/distributors/new': {
      id: '/app/admin/distributors/new'
      path: '/new'
      fullPath: '/app/admin/distributors/new'
      preLoaderRoute: typeof AppAdminDistributorsNewRouteImport
      parentRoute: typeof AppAdminDistributorsRoute
    }
  }
}

interface AppAdminDistributorsRouteChildren {
  AppAdminDistributorsNewRoute: typeof AppAdminDistributorsNewRoute
}

const AppAdminDistributorsRouteChildren: AppAdminDistributorsRouteChildren = {
  AppAdminDistributorsNewRoute: AppAdminDistributorsNewRoute,
}

const AppAdminDistributorsRouteWithChildren =
  AppAdminDistributorsRoute._addFileChildren(AppAdminDistributorsRouteChildren)

interface AppAdminOnboardingRouteChildren {
  AppAdminOnboardingNewRoute: typeof AppAdminOnboardingNewRoute
}

const AppAdminOnboardingRouteChildren: AppAdminOnboardingRouteChildren = {
  AppAdminOnboardingNewRoute: AppAdminOnboardingNewRoute,
}

const AppAdminOnboardingRouteWithChildren =
  AppAdminOnboardingRoute._addFileChildren(AppAdminOnboardingRouteChildren)

interface AppAdminOrdersRouteChildren {
  AppAdminOrdersNewRoute: typeof AppAdminOrdersNewRoute
}

const AppAdminOrdersRouteChildren: AppAdminOrdersRouteChildren = {
  AppAdminOrdersNewRoute: AppAdminOrdersNewRoute,
}

const AppAdminOrdersRouteWithChildren = AppAdminOrdersRoute._addFileChildren(
  AppAdminOrdersRouteChildren,
)

interface AppAdminRmsRouteChildren {
  AppAdminRmsNewRoute: typeof AppAdminRmsNewRoute
}

const AppAdminRmsRouteChildren: AppAdminRmsRouteChildren = {
  AppAdminRmsNewRoute: AppAdminRmsNewRoute,
}

const AppAdminRmsRouteWithChildren = AppAdminRmsRoute._addFileChildren(
  AppAdminRmsRouteChildren,
)

interface AppDistributorOnboardingRouteChildren {
  AppDistributorOnboardingNewRoute: typeof AppDistributorOnboardingNewRoute
}

const AppDistributorOnboardingRouteChildren: AppDistributorOnboardingRouteChildren =
  {
    AppDistributorOnboardingNewRoute: AppDistributorOnboardingNewRoute,
  }

const AppDistributorOnboardingRouteWithChildren =
  AppDistributorOnboardingRoute._addFileChildren(
    AppDistributorOnboardingRouteChildren,
  )

interface AppDistributorOrdersRouteChildren {
  AppDistributorOrdersNewRoute: typeof AppDistributorOrdersNewRoute
}

const AppDistributorOrdersRouteChildren: AppDistributorOrdersRouteChildren = {
  AppDistributorOrdersNewRoute: AppDistributorOrdersNewRoute,
}

const AppDistributorOrdersRouteWithChildren =
  AppDistributorOrdersRoute._addFileChildren(AppDistributorOrdersRouteChildren)

interface AppInvestorPortfolioRouteChildren {
  AppInvestorPortfolioHoldingIdRoute: typeof AppInvestorPortfolioHoldingIdRoute
}

const AppInvestorPortfolioRouteChildren: AppInvestorPortfolioRouteChildren = {
  AppInvestorPortfolioHoldingIdRoute: AppInvestorPortfolioHoldingIdRoute,
}

const AppInvestorPortfolioRouteWithChildren =
  AppInvestorPortfolioRoute._addFileChildren(AppInvestorPortfolioRouteChildren)

interface AppRmDistributorsRouteChildren {
  AppRmDistributorsNewRoute: typeof AppRmDistributorsNewRoute
}

const AppRmDistributorsRouteChildren: AppRmDistributorsRouteChildren = {
  AppRmDistributorsNewRoute: AppRmDistributorsNewRoute,
}

const AppRmDistributorsRouteWithChildren =
  AppRmDistributorsRoute._addFileChildren(AppRmDistributorsRouteChildren)

interface AppRmOnboardingRouteChildren {
  AppRmOnboardingNewRoute: typeof AppRmOnboardingNewRoute
}

const AppRmOnboardingRouteChildren: AppRmOnboardingRouteChildren = {
  AppRmOnboardingNewRoute: AppRmOnboardingNewRoute,
}

const AppRmOnboardingRouteWithChildren = AppRmOnboardingRoute._addFileChildren(
  AppRmOnboardingRouteChildren,
)

interface AppRmOrdersRouteChildren {
  AppRmOrdersNewRoute: typeof AppRmOrdersNewRoute
}

const AppRmOrdersRouteChildren: AppRmOrdersRouteChildren = {
  AppRmOrdersNewRoute: AppRmOrdersNewRoute,
}

const AppRmOrdersRouteWithChildren = AppRmOrdersRoute._addFileChildren(
  AppRmOrdersRouteChildren,
)

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminBrokerageImportsRoute: typeof AppAdminBrokerageImportsRoute
  AppAdminCommissionsRoute: typeof AppAdminCommissionsRoute
  AppAdminDistributorCategoriesRoute: typeof AppAdminDistributorCategoriesRoute
  AppAdminDistributorsRoute: typeof AppAdminDistributorsRouteWithChildren
  AppAdminMappingsRoute: typeof AppAdminMappingsRoute
  AppAdminMasterDataRoute: typeof AppAdminMasterDataRoute
  AppAdminOnboardingRoute: typeof AppAdminOnboardingRouteWithChildren
  AppAdminOrdersRoute: typeof AppAdminOrdersRouteWithChildren
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminReconciliationRoute: typeof AppAdminReconciliationRoute
  AppAdminRmsRoute: typeof AppAdminRmsRouteWithChildren
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminSystemConfigRoute: typeof AppAdminSystemConfigRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDistributorAumRoute: typeof AppDistributorAumRoute
  AppDistributorCommissionsRoute: typeof AppDistributorCommissionsRoute
  AppDistributorOnboardingRoute: typeof AppDistributorOnboardingRouteWithChildren
  AppDistributorOrdersRoute: typeof AppDistributorOrdersRouteWithChildren
  AppInvestorGoalsRoute: typeof AppInvestorGoalsRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRouteWithChildren
  AppInvestorProfileRoute: typeof AppInvestorProfileRoute
  AppInvestorTaxRoute: typeof AppInvestorTaxRoute
  AppInvestorTransactionsRoute: typeof AppInvestorTransactionsRoute
  AppRmClientsRoute: typeof AppRmClientsRoute
  AppRmDistributorsRoute: typeof AppRmDistributorsRouteWithChildren
  AppRmEarningsRoute: typeof AppRmEarningsRoute
  AppRmOnboardingRoute: typeof AppRmOnboardingRouteWithChildren
  AppRmOrdersRoute: typeof AppRmOrdersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDistributorIndexRoute: typeof AppDistributorIndexRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
  AppRmIndexRoute: typeof AppRmIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminBrokerageImportsRoute: AppAdminBrokerageImportsRoute,
  AppAdminCommissionsRoute: AppAdminCommissionsRoute,
  AppAdminDistributorCategoriesRoute: AppAdminDistributorCategoriesRoute,
  AppAdminDistributorsRoute: AppAdminDistributorsRouteWithChildren,
  AppAdminMappingsRoute: AppAdminMappingsRoute,
  AppAdminMasterDataRoute: AppAdminMasterDataRoute,
  AppAdminOnboardingRoute: AppAdminOnboardingRouteWithChildren,
  AppAdminOrdersRoute: AppAdminOrdersRouteWithChildren,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminReconciliationRoute: AppAdminReconciliationRoute,
  AppAdminRmsRoute: AppAdminRmsRouteWithChildren,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminSystemConfigRoute: AppAdminSystemConfigRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDistributorAumRoute: AppDistributorAumRoute,
  AppDistributorCommissionsRoute: AppDistributorCommissionsRoute,
  AppDistributorOnboardingRoute: AppDistributorOnboardingRouteWithChildren,
  AppDistributorOrdersRoute: AppDistributorOrdersRouteWithChildren,
  AppInvestorGoalsRoute: AppInvestorGoalsRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRouteWithChildren,
  AppInvestorProfileRoute: AppInvestorProfileRoute,
  AppInvestorTaxRoute: AppInvestorTaxRoute,
  AppInvestorTransactionsRoute: AppInvestorTransactionsRoute,
  AppRmClientsRoute: AppRmClientsRoute,
  AppRmDistributorsRoute: AppRmDistributorsRouteWithChildren,
  AppRmEarningsRoute: AppRmEarningsRoute,
  AppRmOnboardingRoute: AppRmOnboardingRouteWithChildren,
  AppRmOrdersRoute: AppRmOrdersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDistributorIndexRoute: AppDistributorIndexRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
  AppRmIndexRoute: AppRmIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
