/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppRmIndexRouteImport } from './routes/app.rm.index'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as AppDistributorIndexRouteImport } from './routes/app.distributor.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppRmOnboardingRouteImport } from './routes/app.rm.onboarding'
import { Route as AppRmEarningsRouteImport } from './routes/app.rm.earnings'
import { Route as AppRmDistributorsRouteImport } from './routes/app.rm.distributors'
import { Route as AppRmClientsRouteImport } from './routes/app.rm.clients'
import { Route as AppInvestorTransactionsRouteImport } from './routes/app.investor.transactions'
import { Route as AppInvestorTaxRouteImport } from './routes/app.investor.tax'
import { Route as AppInvestorProfileRouteImport } from './routes/app.investor.profile'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorGoalsRouteImport } from './routes/app.investor.goals'
import { Route as AppDistributorOnboardingRouteImport } from './routes/app.distributor.onboarding'
import { Route as AppDistributorCommissionsRouteImport } from './routes/app.distributor.commissions'
import { Route as AppDistributorAumRouteImport } from './routes/app.distributor.aum'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminRmsRouteImport } from './routes/app.admin.rms'
import { Route as AppAdminReconciliationRouteImport } from './routes/app.admin.reconciliation'
import { Route as AppAdminPayoutsRouteImport } from './routes/app.admin.payouts'
import { Route as AppAdminOnboardingRouteImport } from './routes/app.admin.onboarding'
import { Route as AppAdminMasterDataRouteImport } from './routes/app.admin.master-data'
import { Route as AppAdminMappingsRouteImport } from './routes/app.admin.mappings'
import { Route as AppAdminDistributorsRouteImport } from './routes/app.admin.distributors'
import { Route as AppAdminCommissionsRouteImport } from './routes/app.admin.commissions'
import { Route as AppAdminBranchesRouteImport } from './routes/app.admin.branches'
import { Route as AppInvestorPortfolioHoldingIdRouteImport } from './routes/app.investor.portfolio.$holdingId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRmIndexRoute = AppRmIndexRouteImport.update({
  id: '/rm/',
  path: '/rm/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorIndexRoute = AppDistributorIndexRouteImport.update({
  id: '/distributor/',
  path: '/distributor/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppRmOnboardingRoute = AppRmOnboardingRouteImport.update({
  id: '/rm/onboarding',
  path: '/rm/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppRmEarningsRoute = AppRmEarningsRouteImport.update({
  id: '/rm/earnings',
  path: '/rm/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppRmDistributorsRoute = AppRmDistributorsRouteImport.update({
  id: '/rm/distributors',
  path: '/rm/distributors',
  getParentRoute: () => AppRoute,
} as any)
const AppRmClientsRoute = AppRmClientsRouteImport.update({
  id: '/rm/clients',
  path: '/rm/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTransactionsRoute = AppInvestorTransactionsRouteImport.update({
  id: '/investor/transactions',
  path: '/investor/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTaxRoute = AppInvestorTaxRouteImport.update({
  id: '/investor/tax',
  path: '/investor/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorProfileRoute = AppInvestorProfileRouteImport.update({
  id: '/investor/profile',
  path: '/investor/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorGoalsRoute = AppInvestorGoalsRouteImport.update({
  id: '/investor/goals',
  path: '/investor/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorOnboardingRoute =
  AppDistributorOnboardingRouteImport.update({
    id: '/distributor/onboarding',
    path: '/distributor/onboarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppDistributorCommissionsRoute =
  AppDistributorCommissionsRouteImport.update({
    id: '/distributor/commissions',
    path: '/distributor/commissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppDistributorAumRoute = AppDistributorAumRouteImport.update({
  id: '/distributor/aum',
  path: '/distributor/aum',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRmsRoute = AppAdminRmsRouteImport.update({
  id: '/admin/rms',
  path: '/admin/rms',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReconciliationRoute = AppAdminReconciliationRouteImport.update({
  id: '/admin/reconciliation',
  path: '/admin/reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnboardingRoute = AppAdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMasterDataRoute = AppAdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMappingsRoute = AppAdminMappingsRouteImport.update({
  id: '/admin/mappings',
  path: '/admin/mappings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDistributorsRoute = AppAdminDistributorsRouteImport.update({
  id: '/admin/distributors',
  path: '/admin/distributors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCommissionsRoute = AppAdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioHoldingIdRoute =
  AppInvestorPortfolioHoldingIdRouteImport.update({
    id: '/$holdingId',
    path: '/$holdingId',
    getParentRoute: () => AppInvestorPortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRoute
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRoute
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRoute
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRoute
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/distributor': typeof AppDistributorIndexRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/rm': typeof AppRmIndexRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/distributors': typeof AppAdminDistributorsRoute
  '/app/admin/mappings': typeof AppAdminMappingsRoute
  '/app/admin/master-data': typeof AppAdminMasterDataRoute
  '/app/admin/onboarding': typeof AppAdminOnboardingRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/reconciliation': typeof AppAdminReconciliationRoute
  '/app/admin/rms': typeof AppAdminRmsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/distributor/onboarding': typeof AppDistributorOnboardingRoute
  '/app/investor/goals': typeof AppInvestorGoalsRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRouteWithChildren
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/tax': typeof AppInvestorTaxRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/distributors': typeof AppRmDistributorsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/portfolio/$holdingId': typeof AppInvestorPortfolioHoldingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/commissions'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/portfolio/$holdingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/commissions'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin'
    | '/app/distributor'
    | '/app/investor'
    | '/app/rm'
    | '/app/investor/portfolio/$holdingId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/branches'
    | '/app/admin/commissions'
    | '/app/admin/distributors'
    | '/app/admin/mappings'
    | '/app/admin/master-data'
    | '/app/admin/onboarding'
    | '/app/admin/payouts'
    | '/app/admin/reconciliation'
    | '/app/admin/rms'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/distributor/onboarding'
    | '/app/investor/goals'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/tax'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/distributors'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/portfolio/$holdingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/': {
      id: '/app/rm/'
      path: '/rm'
      fullPath: '/app/rm/'
      preLoaderRoute: typeof AppRmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/investor'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/': {
      id: '/app/distributor/'
      path: '/distributor'
      fullPath: '/app/distributor/'
      preLoaderRoute: typeof AppDistributorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/onboarding': {
      id: '/app/rm/onboarding'
      path: '/rm/onboarding'
      fullPath: '/app/rm/onboarding'
      preLoaderRoute: typeof AppRmOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/earnings': {
      id: '/app/rm/earnings'
      path: '/rm/earnings'
      fullPath: '/app/rm/earnings'
      preLoaderRoute: typeof AppRmEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/distributors': {
      id: '/app/rm/distributors'
      path: '/rm/distributors'
      fullPath: '/app/rm/distributors'
      preLoaderRoute: typeof AppRmDistributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/clients': {
      id: '/app/rm/clients'
      path: '/rm/clients'
      fullPath: '/app/rm/clients'
      preLoaderRoute: typeof AppRmClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/transactions': {
      id: '/app/investor/transactions'
      path: '/investor/transactions'
      fullPath: '/app/investor/transactions'
      preLoaderRoute: typeof AppInvestorTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/tax': {
      id: '/app/investor/tax'
      path: '/investor/tax'
      fullPath: '/app/investor/tax'
      preLoaderRoute: typeof AppInvestorTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/profile': {
      id: '/app/investor/profile'
      path: '/investor/profile'
      fullPath: '/app/investor/profile'
      preLoaderRoute: typeof AppInvestorProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/goals': {
      id: '/app/investor/goals'
      path: '/investor/goals'
      fullPath: '/app/investor/goals'
      preLoaderRoute: typeof AppInvestorGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/onboarding': {
      id: '/app/distributor/onboarding'
      path: '/distributor/onboarding'
      fullPath: '/app/distributor/onboarding'
      preLoaderRoute: typeof AppDistributorOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/commissions': {
      id: '/app/distributor/commissions'
      path: '/distributor/commissions'
      fullPath: '/app/distributor/commissions'
      preLoaderRoute: typeof AppDistributorCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/aum': {
      id: '/app/distributor/aum'
      path: '/distributor/aum'
      fullPath: '/app/distributor/aum'
      preLoaderRoute: typeof AppDistributorAumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/rms': {
      id: '/app/admin/rms'
      path: '/admin/rms'
      fullPath: '/app/admin/rms'
      preLoaderRoute: typeof AppAdminRmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/reconciliation': {
      id: '/app/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/app/admin/reconciliation'
      preLoaderRoute: typeof AppAdminReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payouts': {
      id: '/app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/app/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/onboarding': {
      id: '/app/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/app/admin/onboarding'
      preLoaderRoute: typeof AppAdminOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/master-data': {
      id: '/app/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/app/admin/master-data'
      preLoaderRoute: typeof AppAdminMasterDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/mappings': {
      id: '/app/admin/mappings'
      path: '/admin/mappings'
      fullPath: '/app/admin/mappings'
      preLoaderRoute: typeof AppAdminMappingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/distributors': {
      id: '/app/admin/distributors'
      path: '/admin/distributors'
      fullPath: '/app/admin/distributors'
      preLoaderRoute: typeof AppAdminDistributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/commissions': {
      id: '/app/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/app/admin/commissions'
      preLoaderRoute: typeof AppAdminCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/branches': {
      id: '/app/admin/branches'
      path: '/admin/branches'
      fullPath: '/app/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio/$holdingId': {
      id: '/app/investor/portfolio/$holdingId'
      path: '/$holdingId'
      fullPath: '/app/investor/portfolio/$holdingId'
      preLoaderRoute: typeof AppInvestorPortfolioHoldingIdRouteImport
      parentRoute: typeof AppInvestorPortfolioRoute
    }
  }
}

interface AppInvestorPortfolioRouteChildren {
  AppInvestorPortfolioHoldingIdRoute: typeof AppInvestorPortfolioHoldingIdRoute
}

const AppInvestorPortfolioRouteChildren: AppInvestorPortfolioRouteChildren = {
  AppInvestorPortfolioHoldingIdRoute: AppInvestorPortfolioHoldingIdRoute,
}

const AppInvestorPortfolioRouteWithChildren =
  AppInvestorPortfolioRoute._addFileChildren(AppInvestorPortfolioRouteChildren)

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminCommissionsRoute: typeof AppAdminCommissionsRoute
  AppAdminDistributorsRoute: typeof AppAdminDistributorsRoute
  AppAdminMappingsRoute: typeof AppAdminMappingsRoute
  AppAdminMasterDataRoute: typeof AppAdminMasterDataRoute
  AppAdminOnboardingRoute: typeof AppAdminOnboardingRoute
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminReconciliationRoute: typeof AppAdminReconciliationRoute
  AppAdminRmsRoute: typeof AppAdminRmsRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDistributorAumRoute: typeof AppDistributorAumRoute
  AppDistributorCommissionsRoute: typeof AppDistributorCommissionsRoute
  AppDistributorOnboardingRoute: typeof AppDistributorOnboardingRoute
  AppInvestorGoalsRoute: typeof AppInvestorGoalsRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRouteWithChildren
  AppInvestorProfileRoute: typeof AppInvestorProfileRoute
  AppInvestorTaxRoute: typeof AppInvestorTaxRoute
  AppInvestorTransactionsRoute: typeof AppInvestorTransactionsRoute
  AppRmClientsRoute: typeof AppRmClientsRoute
  AppRmDistributorsRoute: typeof AppRmDistributorsRoute
  AppRmEarningsRoute: typeof AppRmEarningsRoute
  AppRmOnboardingRoute: typeof AppRmOnboardingRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDistributorIndexRoute: typeof AppDistributorIndexRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
  AppRmIndexRoute: typeof AppRmIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminCommissionsRoute: AppAdminCommissionsRoute,
  AppAdminDistributorsRoute: AppAdminDistributorsRoute,
  AppAdminMappingsRoute: AppAdminMappingsRoute,
  AppAdminMasterDataRoute: AppAdminMasterDataRoute,
  AppAdminOnboardingRoute: AppAdminOnboardingRoute,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminReconciliationRoute: AppAdminReconciliationRoute,
  AppAdminRmsRoute: AppAdminRmsRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDistributorAumRoute: AppDistributorAumRoute,
  AppDistributorCommissionsRoute: AppDistributorCommissionsRoute,
  AppDistributorOnboardingRoute: AppDistributorOnboardingRoute,
  AppInvestorGoalsRoute: AppInvestorGoalsRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRouteWithChildren,
  AppInvestorProfileRoute: AppInvestorProfileRoute,
  AppInvestorTaxRoute: AppInvestorTaxRoute,
  AppInvestorTransactionsRoute: AppInvestorTransactionsRoute,
  AppRmClientsRoute: AppRmClientsRoute,
  AppRmDistributorsRoute: AppRmDistributorsRoute,
  AppRmEarningsRoute: AppRmEarningsRoute,
  AppRmOnboardingRoute: AppRmOnboardingRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDistributorIndexRoute: AppDistributorIndexRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
  AppRmIndexRoute: AppRmIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
